// bedroom = water, bathroom = waste

export const listData = [
    {
      id: 1,
      title: "1BHK Near Amrit Science Campus",
      img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "included",
      waste: "included",
      power: "15 per unit",
      price: 1000,
      address: "456 Park Avenue, London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
      id: 2,
      title: "Double room near LOD",
      img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "included",
      waste: "included",
      power: "20 per unit",
      price: 1500,
      address: "789 Oxford Street, London",
      latitude: 52.4862,
      longitude: -1.8904,
    },
    {
      id: 3,
      title: "A New Apartment in Lainchur!",
      img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "Seperate",
      waste: "Seperate",
      power: "14 per unit",
      price: 800,
      address: "101 Baker Street, London",
      latitude: 53.4808,
      longitude: -2.2426,
    },
    {
      id: 4,
      title: "2BHK for Famliy near Baneswor",
      img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "included",
      waste: "Seperate",
      power: "18 per unit",
      price: 1000,
      address: "234 Kingsway, London,",
      latitude: 53.8008,
      longitude: -1.5491,
    },
    {
      id: 5,
      title: "Single room for student",
      img: "https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "Seperate",
      waste: "Included",
      power: "16 per unit",
      price: 1500,
      address: "567 Victoria Road, London",
      latitude: 53.4084,
      longitude: -2.9916,
    },
    {
      id: 6,
      title: "Apartment near kamalphokari",
      img: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "Seperate",
      waste: "Seperate",
      power: "12 per unit",
      price: 800,
      address: "890 Regent Street, London",
      latitude: 54.9783,
      longitude: -1.6174,
    },
    {
      id: 7,
      title: "Single room available near Newroad",
      img: "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "Included",
      waste: "Seperate",
      power: "14 per unit",
      price: 1000,
      address: "112 Piccadilly, London",
      latitude: 53.3811,
      longitude: -1.4701,
    },
    {
      id: 8,
      title: "1BHK available at Gangabu",
      img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      water: "Included",
      waste: "Seperate",
      power: "15 per unit",
      price: 1500,
      address: "8765 Main High Street, London",
      latitude: 51.4545,
      longitude: -2.5879,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Beautiful Apartment at lainchaur",
    price: 1200,
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    water: "Included",
    waste: "Excluded",
    power: "15 per unit",
    size: 861,
    latitude: 51.5074,
    longitude: -0.1278,
    city: "London",
    address: "1234 Broadway St",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  
  export const userData = {
    id: 1,
    name: "John Doe",
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  };